/** Paths to 24×24 SVG assets in /public/icons */

export const ICONS = {
  solvedLogo: "/icons/solved-logo.svg",
  chat: "/icons/chat-icon.svg",
  createImage: "/icons/create-image-icon.svg",
  createVideo: "/icons/create-video-icon.svg",
  imageEditor: "/icons/image-editor-icon.svg",
  files: "/icons/files-icon.svg",
  filter: "/icons/filter-icon.svg",
  listView: "/icons/list-view-icon.svg",
  filesListFolder: "/icons/folder-icon.svg",
  filesEmptyFolder: "/icons/empty-folder-icon.svg",
  filesListFile: "/icons/file-icon.svg",
  filesListImage: "/icons/image-file-icon.svg",
  filesListMovie: "/icons/movie-file-icon.svg",
  filesToolbarUpload: "/icons/upload-icon.svg",
  filesToolbarAddFolder: "/icons/add-folder-icon.svg",
  filesToolbarNewFile: "/icons/add-files-icon.svg",
  filesHeaderAddUser: "/icons/add-user-icon.svg",
  history: "/icons/history-icon.svg",
  liked: "/icons/liked-icon.svg",
  likedOutlined: "/icons/liked-outlined-icon.svg",
  likedFilled: "/icons/liked-filled-icon.svg",
  rename: "/icons/rename-icon.svg",
  pin: "/icons/pin-icon.svg",
  delete: "/icons/delete-icon.svg",
  settings: "/icons/master-settings-icon.svg",
  templates: "/icons/templates-icon.svg",
  socialMedia: "/icons/social-media-icon.svg?v=2",
  email: "/icons/email-icon.svg",
  digitalMedia: "/icons/digital-media-icon.svg",
  attachPrompt: "/icons/attach-prompt-icon.svg?v=2",
  generateButton: "/icons/generate-button.svg",
  aspect16x9: "/icons/16x9-aspect-icon.svg",
  aspect1x1: "/icons/1x1-aspect-icon.svg",
  aspect4x5: "/icons/4x5-aspect-icon.svg",
  aspect9x16: "/icons/9x16-aspect-icon.svg",
  resolutionDiamond: "/icons/resolution-diamond-icon.svg",
  masterSettings: "/icons/master-settings-icon.svg",
  imagePlaceholder: "/icons/image-placeholder-icon.svg",
  videoPlaceholder: "/icons/video-placeholder-icon.svg",
  promptBar: "/icons/prompt-bar.svg",
  copy: "/icons/copy-icon.svg",
  threeDots: "/icons/3-dots-icon.svg",
  editorAdd: "/icons/editor-add-icon.svg",
  editorRemove: "/icons/editor-remove-icon.svg",
  editorEnhance: "/icons/editor-enhance-icon.svg",
  editorRegenerate: "/icons/editor-regenerate-icon.svg",
  regenerate: "/icons/regenerate-icon.svg",
  thumbsUp: "/icons/thumbs-up-icon.svg",
  thumbsDown: "/icons/thumbs-down-icon.svg",
  editorTextTool: "/icons/editor-text-tool-icon.svg",
  editorColorSwatch: "/icons/editor-color-swatch-icon.svg",
  editorDraw: "/icons/editor-draw-icon.svg",
} as const;

export type IconPath = (typeof ICONS)[keyof typeof ICONS];
